services:
  antispam-telegramm-bot:
    build:
      context: ./bot
      target: dev
    container_name: telegramm_antispam_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/bot
